[schemes]
name = "Schemes"

[schemes.balance]
name = "Balance"

[schemes.balance.isocolon]
name = "Isocolon"
description = "A series of similarly structured elements having the same length."
quote = "Want some, get some"
example = ""

[schemes.balance.tricolon]
name = "Tricolon"
description = "Three parallel elements of the same length occuring together."
quote = "I came, I saw, I conquered --Caesar"
example = ""

[schemes.balance.parallelism]
name = "Parallelism"
description = "Similarity of structure in a pair or series of related wordds, phrases, or clauses."
quote = "Give a man a fish and you feed him for a day; teach a man to fish and you feed him for a lifetime. --proverb"
example = ""

[schemes.balance.climax]
name = "Climax"
description = "Generally, the arrangement of words, phrases, or clauses in an order of increasing importance, often in parallel structure."
quote = "...O'erthrows thy joys, friends, fortune and thy state --William Shakespeare from Richard II"
example = ""

[schemes.balance.bathos]
name = "Bathos or anti-climax"
description = "The least important items appears either anticlimatically or unexpectedly."
quote = "Die and endow a college or a cat."
example = ""

[schemes.balance.antithesis]
name = "Antithesis"
description = "Juxtaposition of contrasting ideas (often in parallel structure)."
quote = [
"Man proposes, God disposes.",
"I came not to bring peace but a sword. --St Matthew's Gospel, 10:34"
]
example = ""

[schemes.balance.chiasmus]
name = "Chiasmus"
description = "Repetition of grammatical structures in reverse order in successive phrases or clauses (not to be mistaken with antimetabole)."
quote = [
"By day the frolic, and the dance by night. --Samuel Johnson, The Vanity of Human Wishes (1794)",
"Despised, if ugly; if she's fair, betrayed. -- Mary Leapor, Essay on Woman"
]
example = ""

[schemes.balance.alliosis]
name = "Alliosis"
description = "A presentation of alternatives, such as a dichotomy."
quote = ""
example = ""

[schemes.changes]
name = "Changes"

[schemes.changes.anastrophe]
name = "Anastrophe"
description = "Inversion of natural order, such as switching adjective and noun."
quote = ""
example = ""

[schemes.changes.parenthesis]
name = "Parenthesis"
description = "Insertion of a verbal unit that interrupts normal syntactical flow."
quote = ""
example = ""

[schemes.changes.hyperbaton]
name = "Hyperbaton"
description = "Pushing or pulling a word where it is not expected."
quote = ""
example = ""

[schemes.changes.metaplasmus]
name = "Metaplasmus"
description = "Misspelling a word."
quote = ""
example = ""

[schemes.changes.enallage]
name = "Enallage"
description = "Intentionally misuse grammar."
quote = ""
example = ""

[schemes.changes.tsmesis]
name = "Tsmesis"
description = "Splitting a word in two with a word or space."
quote = ""
example = ""

[schemes.omission]
name = "Omission"

[schemes.omission.ellipsis]
name = "Ellipsis"
description = "Omission of a word or words readily implied by context."
quote = ""
example = ""

[schemes.omission.brachylogia]
name = "Brachylogia"
description = "Omission of conjuctions between a series of words."
quote = ""
example = ""

[schemes.omission.asyndeton]
name = "Asyndeton"
description = "Omission of conjunction between a series of clauses to create speed and brevity."
quote = ""
example = ""

[schemes.omission.polysyndeton]
name = "Polysyndeton"
description = "Opposite of asyndeton, a superabundance of conjuctions meant to overwhelm."
quote = ""
example = ""

[schemes.repetition]
name = "Repetition"

[schemes.repetition.words]
name = "Words"

[schemes.repetition.words.polyptoton]
name = "Polyptoton"
description = "Repetition of words derived from the same root."
quote = ""
example = ""

[schemes.repetition.words.antanaclasis]
name = "Antanaclasis"
description = "Repetition of a word in two different senses."
quote = ""
example = ""

[schemes.repetition.words.anaphora]
name = "Anaphora"
description = "Repetition of the same word or group of words at the beginning of successive clauses."
quote = ""
example = ""

[schemes.repetition.words.epistrophe]
name = "Epistrophe"
description = "Repetition of the same word of group of words at the ends of successive clauses."
quote = ""
example = ""

[schemes.repetition.words.epanalepsis]
name = "Epanalepsis"
description = "Repetition at the end of a clause of the word that occured at the beginning of the clause."
quote = ""
example = ""

[schemes.repetition.words.anadiplosis]
name = "Anadiplosis"
description = "Repetition of the last word of one clause at the beginning of the following clause."
quote = ""
example = ""

[schemes.repetition.words.climax]
name = "Climax"
description = "Repetition of the scheme anadiplosis at least three times, with the elements arranged in an order of increasing importance."
quote = ""
example = ""

[schemes.repetition.words.antimetabole]
name = "Antimetabole"
description = "Repetition of words, in successive clauses, in reverse grammatical order. Sometimes mistaken as chiasmus."
quote = [
"In peace you long for war, and in war you long for peace.",
"Pleasure's a sin, and sometimes sin's a pleasure."
]
example = ""

[schemes.repetition.sounds]
name = "Sounds"

[schemes.repetition.sounds.alliteration]
name = "Alliteration"
description = "Repetition of initial or medial consonants in two or more adjacent words."
quote = ""
example = ""

[schemes.repetition.sounds.assonance]
name = "Assonance"
description = "Repetition of similar vowel sounds, preceded and followed by different consonants, in the stressed syllable of adjacent words."
quote = ""
example = ""

[tropes]
name = "Tropes"

[tropes.reference]
name = "Reference"

[tropes.reference.apostrophe]
name = "Apostrophe"
description = "Addressing someone or some abstraction that is not physically present."
quote = ""
example = ""

[tropes.reference.personification]
name = "Personification"
description = "Reference to abstractions or inanimate objects as though they had human qualities or abilities."
quote = ""
example = ""

[tropes.reference.synecdoche]
name = "Synecdoche"
description = "A whole is represented by naming one of its parts."
quote = ""
example = ""

[tropes.reference.metaphor]
name = "Metaphor"
description = "Reference to one thing as another, treating them as if the same and implying a comparison."
quote = ""
example = ""

[tropes.reference.simile]
name = "Simile"
description = "Explicit comparison of one thing to another (analogy)."
quote = ""
example = ""

[tropes.reference.metonymy]
name = "Metonymy"
description = "Reference to something or someone by naming one of its attributes."
quote = ""
example = ""

[tropes.wordplay]
name = "Wordplay"

[tropes.wordplay.antanaclasis]
name = "Antanaclasis"
description = "Repetition of a word in two different senses"
quote = ""
example = ""

[tropes.wordplay.paranomasia]
name = "Paranomasia (pun)"
description = "Using words that sound alike but that differ in meaning, a pun."
quote = ""
example = ""

[tropes.wordplay.syllepsis]
name = "Syllepsis"
description = "Using a word differently un relation to two or more words that it modifies or governs (sometimes called zeugma)."
quote = ""
example = ""

[tropes.wordplay.onomatopoeia]
name = "Onomatopoeia"
description = "Use of words whose sound correspond with their semantic value."
quote = ""
example = ""

